[COMMON]
ProjectName = data-migration
ThreadCount = 20
LocalDownloadPath = C:\Users\shinminbeom\
LocalSeparator = \
VolumesPlaceHolder = data1 | data2 | data3

[S3]
# src
SrcRootPath = /khulab-miracurenas01/Proteomics/astral_data/

# dst
DstRootPath = /oncx-dl-raw-dev/
